import path from 'node:path';
import { createTwoFilesPatch } from 'diff';
import { CONFIG_FILENAME, type Config, type SectionId, SECTION_IDS } from '../config/schema.js';
import { loadConfig, renderDefaultConfig } from '../config/load.js';
import { resolvePackages, type ResolvedPackage } from '../config/packages.js';
import {
  parseReadme,
  findHeading,
  headingContentEnd,
  renderRegion,
  type ParsedReadme,
} from '../markdown/markers.js';
import { exists, readTextIfExists, writeText } from '../util/fs.js';
import { GENERATORS } from '../extractors/registry.js';
import { log } from '../util/log.js';

export interface InitOptions {
  repoRoot: string;
  adopt: boolean;
  dryRun: boolean;
  configPath?: string;
}

export interface InitResult {
  wroteConfig: boolean;
  readmes: Array<{
    path: string;
    before: string;
    after: string;
    inserted: SectionId[];
    adopted: SectionId[];
    skipped: Array<{ id: SectionId; why: string }>;
  }>;
}

const PLACEHOLDER =
  '_This section is generated by readme-sync. Run `readme-sync update` to populate it._';

/**
 * Insert marker pairs into the README at configured anchors. Without --adopt an
 * existing heading gets an *empty* marker pair right below it and its prose is
 * left alone. With --adopt the prose under the heading (up to the next heading
 * of the same or higher level) is moved inside the markers and will be
 * replaced on the next update.
 */
export async function init(opts: InitOptions): Promise<InitResult> {
  const configFile = path.join(opts.repoRoot, opts.configPath ?? CONFIG_FILENAME);
  let wroteConfig = false;
  if (!(await exists(configFile))) {
    if (!opts.dryRun) await writeText(configFile, renderDefaultConfig());
    wroteConfig = true;
  }
  const config: Config = (await exists(configFile))
    ? (await loadConfig(opts.repoRoot, opts.configPath)).config
    : (await loadConfig(opts.repoRoot)).config;
  const effective =
    wroteConfig && opts.dryRun
      ? (await import('../config/load.js')).parseConfig(
          (await import('yaml')).default.parse(renderDefaultConfig()),
        )
      : config;
  const packages = await resolvePackages(opts.repoRoot, effective);
  const result: InitResult = { wroteConfig, readmes: [] };

  for (const pkg of packages) {
    const before = (await readTextIfExists(pkg.absReadme)) ?? defaultReadme(pkg);
    const { after, inserted, adopted, skipped } = insertMarkers(before, pkg, opts.adopt);
    result.readmes.push({ path: pkg.readme, before, after, inserted, adopted, skipped });
    if (!opts.dryRun && after !== before) await writeText(pkg.absReadme, after);
  }
  return result;
}

function defaultReadme(pkg: ResolvedPackage): string {
  const name = pkg.path === '.' ? path.basename(pkg.absPath) : pkg.path.split('/').pop()!;
  return `# ${name}\n\n`;
}

export function insertMarkers(
  source: string,
  pkg: ResolvedPackage,
  adopt: boolean,
): {
  after: string;
  inserted: SectionId[];
  adopted: SectionId[];
  skipped: Array<{ id: SectionId; why: string }>;
} {
  const inserted: SectionId[] = [];
  const adopted: SectionId[] = [];
  const skipped: Array<{ id: SectionId; why: string }> = [];
  let doc = source;

  // Process in generator order so appended sections have a stable order.
  const order = GENERATORS.map((g) => g.id).filter((id): id is SectionId =>
    (SECTION_IDS as readonly string[]).includes(id),
  );
  for (const id of order) {
    const cfg = pkg.sections[id];
    if (!cfg.enabled) continue;
    let parsed: ParsedReadme;
    try {
      parsed = parseReadme(doc);
    } catch (err) {
      skipped.push({ id, why: (err as Error).message });
      continue;
    }
    if (parsed.regions.some((r) => r.id === id)) {
      skipped.push({ id, why: 'marker already present' });
      continue;
    }
    const anchor = cfg.anchor;
    if (!anchor) {
      skipped.push({ id, why: 'no anchor configured' });
      continue;
    }
    const heading = findHeading(parsed, anchor);
    if (heading) {
      const contentEnd = headingContentEnd(parsed, heading);
      const existing = doc.slice(heading.end, contentEnd);
      if (adopt && existing.trim()) {
        // Wrap the existing prose; it will be replaced on the next update.
        const body = existing.replace(/^\s+|\s+$/g, '');
        // Refuse to adopt if the prose contains other markers.
        if (/<!--\s*autogen:/.test(body)) {
          skipped.push({ id, why: 'content under anchor contains other autogen markers' });
          continue;
        }
        doc =
          doc.slice(0, heading.end) +
          '\n\n' +
          renderRegion(id, body) +
          '\n' +
          trailingGap(doc, contentEnd) +
          doc.slice(contentEnd);
        adopted.push(id);
      } else {
        doc =
          doc.slice(0, heading.end) +
          '\n\n' +
          renderRegion(id, PLACEHOLDER) +
          '\n' +
          doc.slice(heading.end);
        inserted.push(id);
      }
    } else {
      const level = /^#+/.exec(anchor.trim())?.[0] ?? '##';
      const title = anchor.replace(/^\s*#{1,6}\s*/, '').trim();
      const sep = doc.endsWith('\n\n') ? '' : doc.endsWith('\n') ? '\n' : '\n\n';
      doc = doc + `${sep}${level} ${title}\n\n${renderRegion(id, PLACEHOLDER)}\n`;
      inserted.push(id);
    }
  }
  return { after: doc, inserted, adopted, skipped };
}

function trailingGap(doc: string, at: number): string {
  // Keep a blank line before the next heading (if any).
  return at < doc.length && !doc.startsWith('\n\n', at - 2) ? '\n' : '';
}

export function unifiedDiff(file: string, before: string, after: string): string {
  if (before === after) return '';
  return createTwoFilesPatch(`a/${file}`, `b/${file}`, before, after, '', '', { context: 3 });
}

export function printInitResult(res: InitResult, dryRun: boolean): void {
  if (res.wroteConfig) log.out(`${dryRun ? 'would create' : 'created'} ${CONFIG_FILENAME}`);
  for (const r of res.readmes) {
    const diff = unifiedDiff(r.path, r.before, r.after);
    if (r.inserted.length)
      log.out(
        `${r.path}: ${dryRun ? 'would insert' : 'inserted'} markers for ${r.inserted.join(', ')}`,
      );
    if (r.adopted.length)
      log.out(
        `${r.path}: ${dryRun ? 'would adopt' : 'adopted'} existing content for ${r.adopted.join(', ')}`,
      );
    for (const s of r.skipped) log.out(`${r.path}: skipped ${s.id} (${s.why})`);
    if (diff) log.out(diff);
  }
}
